# https://taskfile.dev

version: "3"

vars:
  DOCKER_IMAGE: ghcr.io/adrianliechti/loop-tunnel

tasks:
  push:
    cmds:
      - docker buildx build --push --platform linux/arm64,linux/amd64 --tag {{.DOCKER_IMAGE}} .
